# Generated by Django 4.2.9 on 2024-01-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('ground_id', models.AutoField(primary_key=True, serialize=False)),
                ('ground_name', models.CharField(max_length=35)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=35)),
                ('contact', models.IntegerField(max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='ground_img/')),
            ],
        ),
    ]
