# Generated by Django 4.2.9 on 2024-01-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_battermodel_bowler_match_player_scorecard_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
